---
title: "Phylo tree methods"
author: "Sophia Horigan"
date: "6/30/2022"
output:
  pdf_document: default
  html_document: default
---

## Building a phylogenetic tree

This tutorial outlines methods for building a maximum-likelihood phylogenetic tree using the program RAxML, and time/phylogeography trees using BEAST1 and BEAST2

############################################
### Full-genome Astrovirus phylogeny
############################################

1. I scraped full genome non-bat host **reference** nucleotide sequences from  NCBI-virus (https://www.ncbi.nlm.nih.gov/labs/virus/vssi/#/).
Search:
* Astroviridae (tax id 39733)
* unclassified Astroviridae (tax id 352926)

with selections Sequence Type = RefSeq, RefSeq Genome Completeness = complete.
Total = 49

2. I scraped full genome bat nucleotide sequences from NCBI-virus (https://www.ncbi.nlm.nih.gov/labs/virus/vssi/#/).
Search:
* Astroviridae (tax id 39733)
* unclassified Astroviridae (tax id 352926)

with selections Nucleotide Completeness = complete, Host = Chiroptera (tax id 30560)
Total = 10

49 + 10 + 2 (my full) = 61 sequences
 
3. Cutoffs
To help alignment, I decided to cut any sequences that were less than 6kb (based on length)
This left 48 sequences.

3. Outgroup
Inlcuding one turkey avastrovirus as the outgroup. thus, I removed all other avastrovirus sequences. so now I have 43 total sequences.

4. Alignment
I aligned the 43 complete sequences in Genious using Multiple Alignment -> MAFFT on default settings.

I added in three more basically full bat seqs-- 2 from denmark, 1 from cameroon

TOTAL = 46

Then, removed 2 sneaky bastrovirus sequences

TOTAL = 44

5. export to modeltest-ng on midway
AIC	  model              K            lnL          score          delta    weight
--------------------------------------------------------------------------------
       1  TVM+I+G4           9   -281433.4796    563062.9592         0.0000    0.6843
       2  GTR+I+G4          10   -281433.2533    563064.5065         1.5473    0.3157
       3  SYM+I+G4           7   -281481.7583    563155.5165        92.5573    0.0000
       4  TVMef+I+G4         6   -281485.7646    563161.5292        98.5699    0.0000
       5  TVM+G4             8   -281519.8495    563233.6990	   170.7398    0.0000
       6  GTR+G4             9   -281547.6399    563291.2799	   228.3206    0.0000
       7  SYM+G4             6   -281586.6430    563363.2860	   300.3267    0.0000
       8  TVMef+G4           5   -281591.2201    563370.4402	   307.4810    0.0000
       9  TPM2uf+I+G4        7   -281591.9912    563375.9823	   313.0231    0.0000
      10  TIM2+I+G4          8   -281591.3448    563376.6896	   313.7303    0.0000
--------------------------------------------------------------------------------
Best model according to AIC
---------------------------
Model:              TVM+I+G4
lnL:                -281433.4796
Frequencies:        0.2538 0.2466 0.2366 0.2630
Subst. Rates:       2.1474 3.5326 1.3328 1.2526 3.5326 1.0000

ML TREE
1. upload onto midway2

2. check alignment works
raxml-ng-mpi --check --msa alignment.phy --model TVM+I+G4 --prefix T1

3. compute threads
raxml-ng-mpi --parse --msa alignment.phy --model TVM+I+G4 --prefix T2

threads = 6

5. did it converge?
`raxml-ng-mpi --bsconverge --bs-trees T3.raxml.bootstraps --prefix T4 --seed 2 --threads 6`
converged after only 200 trees! maybe the sequences are just so divergent that it worked out?

6. because it converged, bring folder onto desktop to examine tree etc.


have support.FBP and support.TBE


############################################
### ML RdRp tree - Madagascar 
############################################

Create an ML RdRp tree using all published Madagascar seqs and our new Mada seqs

CREATE DATASET
1. determine how many of my samples have the complete RdRp gene
-we only have 2, contained within the full genomes

2. get all published Madabat RdRp seqs
-2 sources:
  -1: Hoarau et al 2021 : https://virologyj.biomedcentral.com/articles/10.1186/s12985-021-01673-2
  -2: Lebarbenchon et al 2017 : https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5520320/
  
  total seqs (with my 2 novel = 67)

ALIGNMENT
3. Align in Geneious prime using MAFFT default settings and trim alignment

4. Export alignment as .fasta to modeltest-ng folder

MODELTEST-NG
5. scp folder with alignment and batch script to midway
`scp -r /Users/sophiahorigan/Documents/GitHub/Mada-Bat-Astro/modeltest-ng/ shorigan@midway2.rcc.uchicago.edu:/home/shorigan/`

6. execute batch script
`chmod 0700 modeltestbash.sbatch`
`./modeltestbash.sbatch`
##
contents of modeltestbash.sbach:
#!/bin/bash
#SBATCH --job-name=batAstro
#SBATCH --account=cbrook
#SBATCH --partition=broadwl
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH --cpus-per-task=1
#SBATCH --time=36:00:00

module load python

conda activate /project2/cbrook/software/modeltest_env

modeltest-ng -i alignment.fasta -t ml -p 8

scp -r shorigan@midway2.rcc.uchicago.edu:/home/shorigan/modeltest-ng/alignment.fasta.out /Users/sophiahorigan/Documents/GitHub/Mada-Bat-Astro/modeltest-ng/

conda deactivate
##

output : 
Summary:

Partition 1/1:
                         Model         Score        Weight
----------------------------------------------------------
       BIC         TPM2uf+I+G4    28051.7731        0.5345
       AIC            TVM+I+G4    27482.2826        0.7046
      AICc            TVM+I+G4    27617.2826        0.7088


RAXML-NG
6. Export alignment as .phy to raxml-ng directory, and move directory to midway

7. load raxml-ng
`module load openmpi/3.0.0+gcc-10.1.0`
`export PATH=/project2/cbrook/software/raxml-ng/bin:$PATH`

8. make sure it will work with your specific model and alignment
`raxml-ng-mpi --check --msa alignment.phy --model TPM2uf+I+G4 --prefix T1`

9. check for number of recommended threads
`raxml-ng-mpi --parse --msa alignment.phy --model TPM2uf+I+G4 --prefix T2`
in this case, recommended threads/MPI processes = 1

10. modify sbatch script to include correct model and number of threads

in this case, looks like this...
#!/bin/bash
#SBATCH --job-name=raxml-ng
#SBATCH --account=cbrook
#SBATCH --partition=broadwl
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH --cpus-per-task=1
#SBATCH --time=36:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=shorigan@uchicago.edu


`raxml-ng-mpi --all --msa alignment.phy --model TPM2uf+I+G4 --prefix T3 --seed 2 --threads 1 --bs-metric fbp,tbe --bs-trees 1000`

Update: had to manually set the number of bootstraps at 1000, and it did not converge! but was close. going to add 200 more bootstraps 

Check convergence using 
`raxml-ng-mpi --bsconverge --bs-trees T3.raxml.bootstraps --prefix T4 --seed 2 --threads 1`

Run 200 more bootstraps
`raxml-ng --bootstrap --msa alignment.phy --model TPM2uf+I+G4 --prefix T5 --seed 333 --threads 1 --bs-trees 200 --bs-metric fbp,tbe`

Concatenate bootstraps
`cat T3.raxml.bootstraps T5.raxml.bootstraps > allbootstraps`

Re-assess convergence
`raxml-ng-mpi --bsconverge --bs-trees allbootstraps --prefix T6 --seed 2 --threads 1 --bs-cutoff 0.03`

Not converged yet! but still getting there. going to add 500 more bootstraps (T7 - T2)
`raxml-ng --bootstrap --msa alignment.phy --model TPM2uf+I+G4 --prefix T7 --seed 666 --bs-trees 500 --bs-metric fbp,tbe`

Hooray, converged after 1650 bootstraps!

Map BS support values onto best-scoring/best-known ML tree, using .besttree generated in the original run
`raxml-ng-mpi --support --tree T3.raxml.bestTree --bs-trees allbootstraps --prefix T13 --threads 1`

Tree with support saved as
`T3.raxml.supportFPB` and `T3.raxml.supportTBE`

Scp back to local computer, import into R to use with phylogenies.R to make trees
1. copy contents into new directory and save on Github (so I can delete and re-upload new empty version of raxml-ng)
`cp -r raxml-ng/* raxml-ng-ML-RdRp-Mada`


############################################
### ML RdRp tree - SWIO 
############################################
Goal: make an ML tree including RdRp seqs from SWIO area to start investigating some biogeographical patterns 

GATHER SEQUENCES
1. To the file containing the Madagascar RdRp seqs from the previous tree (plus our two novel seqs), I added SWIO seqs that I found as a result of a lit search. I located seqs from Reunion Island and Mozambique. Altogether, there are now 125 sequences.

ALIGNMENT
1. In Geneious Prime, I aligned the RdRp sequences using default settings. (same turkey avastrovirus outgroup as other trees)

2. Didn't even need to trim becuase all of the sequences were basically the same length, woohoo!

MODEL TEST
1. export alignment as a .fasta for model test

2. put into modeltest-ng directory

3. move directory to midway and run

output: 

AIC	  model              K            lnL          score          delta    weight
--------------------------------------------------------------------------------
       1  TVM+I+G4           9    -22490.9303     45493.8606         0.0000    0.4659
       2  TPM2uf+I+G4        7    -22493.1371     45494.2743         0.4136    0.3789
       3  TIM2+I+G4          8    -22493.0700     45496.1400         2.2794    0.1490
       4  GTR+I+G4          10    -22494.2511     45502.5022         8.6416    0.0062
       5  TPM3uf+I+G4        7    -22510.7127     45529.4254        35.5648    0.0000
       6  TPM1uf+I+G4        7    -22510.8529     45529.7057        35.8451    0.0000
       7  TrN+I+G4           7    -22511.7192     45531.4385        37.5779    0.0000
       8  TIM1+I+G4          8    -22510.8333     45531.6666        37.8060    0.0000
       9  HKY+I+G4           6    -22518.2582     45542.5163        48.6557    0.0000
      10  TIM3+I+G4          8    -22518.5779     45547.1559        53.2953    0.0000
--------------------------------------------------------------------------------

the result: TVM+I+G4


ML TREE
1. export alignment as phylip from geneious into copy of raxml-ng directory

2. move directory to midway

3. load raxml-ng

8. make sure it will work with your specific model and alignment
`raxml-ng-mpi --check --msa alignment.phy --model TVM+I+G4 --prefix T1`

9. check for number of recommended threads
`raxml-ng-mpi --parse --msa alignment.phy --model TVM+I+G4 --prefix T2`
threads = 1

* had to run just the ML part, then more boostraps, because it didn't finish -all the first time.
now i have a bestTree file and need to check for convergence before adding support valyes to besttree

8. concatenate bootstraps () and see if it converged
`cat T3.raxml.bootstraps.TMP T6.raxml.bootstraps > allbootstraps`
`raxml-ng-mpi --bsconverge --bs-trees allbootstraps --prefix T7 --seed 2 --threads 1`

it did yayy!! after 1250 bootstraps.

9. make the supported tree.
raxml-ng-mpi --support --tree T5.raxml.bestTree --bs-trees allbootstraps --prefix T8 --threads 1 

best tree is T8.raxml.support

Moving everything off of Midway. success!




############################################
### ML RdRp tree - Africa 
############################################
1. Lit search of all astrovirus rdrp seqs from Africa
Madagascar - 2012, 2014, 2018
Mozambique - 2015
Reunion - 2017, 2018
Kenya - ?
Gabon - 2009
Egypt - 2016
DRC - 2012
Tanzania - 2013
Cameroon - 2013

Total seqs = 298

ALIGNMENT
1. align in geneious using mafft, default settings

2. trim alignment


















BAYESIAN TIMETREE
Going to make a tree using BEAST to infer MRCA of group of SWIO seqs. 
*made a directory in the Github folder called beast

Generate .xml for Bayesian timetree using the program BEAUti (Bayesian Evolutionary Analysis Utility)


slurm script
#!/bin/bash
#SBATCH --job-name=beast
#SBATCH --account=pi-cbrook
#SBATCH --partition=broadwl
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH --ntasks=8
#SBATCH --time=36:00:00

module load midway2
module load java/1.8
module load cuda/8.0
module load beagle/trunk
module load beast/2.6.2

beast -beagle_CPU -seed 777 /home/shorigan/beast/rdrp_swio.xml





